GET http://localhost:3000/products

### 
GET http://localhost:3000/orders

### 
# Post with valid ID
GET http://localhost:3000/products/1


### 
# Post with invalid ID
GET http://localhost:3000/products/239042934023

###
## Login with valid email and password
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "auth": {
    "email": "a@a.com",
    "password": "password"
    }
}
###
## Login with invalid email or password
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "auth": {
    "email": "a@a.com",
    "password": "pas22sword"
    }
}


### 
## Register with a valid details
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "newuser@gmail.com",
    "username": "NewUser",
    "password": "password",
    "password_confirmation": "password"
}

### 
## Register with a invalid details
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "a@a.com",
    "username": "NewUser",
    "password": "password",
    "password_confirmation": "password"
}